### ISSUE TITLE
Does this package supports laravel 8 ? 

### ISSUE THREAD

**Issue by mazraara** [Codeception/module-laravel#1]
Currently getting an error when trying to run test cases in laravel 8

![image](https://user-images.githubusercontent.com/2024844/93078517-3c9bbf00-f6a8-11ea-87b8-c8ff0c832a37.png)

**Comment by TavoNiievez** [comment]
@mazraara [Version 2.0](https://github.com/Codeception/module-laravel/releases/tag/2.0.0 ) is now available!

Support for `Laravel 8` was added.

Your issue should disappear when updating.

In case the issue is still there, you can now use the test project: https://github.com/Codeception/laravel-module-tests so you can reproduce the bug and share it for analysis.

Cheers!
