### ISSUE TITLE
Issue when trying to run Acceptance tests

### ISSUE THREAD

**Issue by starch1ldoff** [Codeception/module-laravel#43]
When trying to run _php vendor/bin/codecept run_ I get such exception:

Typed property Codeception\Module\Laravel::$client must not be accessed before initialization in /opt/project/vendor/codece
ption/lib-innerbrowser/src/Codeception/Lib/InnerBrowser.php:77.

Maybe there is anyone, who experienced such things in laravel installation?

**Comment by Naktibalda** [comment]
I raised pull request to fix this error, but this error masked the root cause in your case, which failed so badly that `_before` method hasn't assigned $client property. https://github.com/Codeception/module-laravel/blob/55d0d106685cfd63cfea57e368e796b1981fdfb4/src/Codeception/Module/Laravel.php#L213

So you will have to fix the root cause.
